export type PageSnapshot = {
  url: string
  text_visit_1: string
  text_visit_2: string
  timers_visit_1: string[]
  timers_visit_2: string[]
  social_proof: string[]
  scarcity: string[]
  prices: string[]
  cta_text: string[]
  element_snippets: string[]
}

export type DetectedPattern = {
  pattern: string
  severity: 'critical' | 'medium' | 'low'
  evidence: string
  explanation: string
  element_html?: string
  evidenceScreenshot?: string   // base64 data URI captured by TinyFish
}

export type ProfileResult = {
  label: string
  prices: string[]
  baseline?: boolean
  discriminated?: boolean
}

export type ProfileComparison = {
  profiles: ProfileResult[]
  discriminationDetected: boolean
  summary: string
}

export type TrustScore = {
  trust_score: number
  verdict: 'trusted' | 'caution' | 'suspicious' | 'dangerous'
  sources_checked: string[]
  signals: string[]
}

export type EthicalConcern = {
  category: 'Data Privacy' | 'Environmental' | 'Labor Practices' | 'Business Practices' | 'Transparency' | 'Consumer Rights'
  severity: 'high' | 'medium' | 'low'
  concern: string
  evidence: string
}

export type EthicalAnalysis = {
  overall: 'concerning' | 'mixed' | 'acceptable' | 'good'
  concerns: EthicalConcern[]
  pages_checked: string[]
}

export type CheckoutAnalysis = {
  productPrice: string
  checkoutTotal: string
  fees: { name: string; amount: string }[]
  preCheckedItems: string[]
  hasAutoRenewal: boolean
  hiddenFeesDetected: boolean
  summary: string
}

export type VisualDarkPattern = {
  type: string
  description: string
  severity: 'critical' | 'medium' | 'low'
  evidenceScreenshot?: string   // base64 data URI of the element captured by TinyFish
}

export type VisualDarkPatterns = {
  visualPatterns: VisualDarkPattern[]
  screenshotObservations: string
}

// ── Action recommendation ─────────────────────────────────────────────────────

export type ActionVerdict = 'safe' | 'sketchy' | 'skip'

export type ActionRecommendation = {
  verdict: ActionVerdict
  headline: string                 // e.g. "540% markup on a $2 AliExpress product"
  topFindings: string[]            // 2-3 bullet points
  ctaLabel: string                 // e.g. "Buy direct for $2.50 →"
  ctaUrl?: string                  // e.g. AliExpress search URL
  ctaSubtext?: string              // e.g. "AliExpress · ships to your region"
  evidenceScreenshot?: string      // the single most compelling screenshot
}

export type SpatialValidation = {
  isValid: boolean
  dimensions: string
  reasoning: string
  comparisonImageUrl?: string  // generated by Nano Banana 2
}

export type VeoValidation = {
  isValid: boolean
  videoUrl: string
  thumbnailUrl: string
  reasoning: string
}

export type ScanResult = {
  risk_score: number
  verdict: string
  patterns: DetectedPattern[]
  profileComparison?: ProfileComparison
  trustScore?: TrustScore
  ethicalAnalysis?: EthicalAnalysis
  checkoutAnalysis?: CheckoutAnalysis
  visualDarkPatterns?: VisualDarkPatterns
  actionRecommendation?: ActionRecommendation
  spatialValidation?: SpatialValidation
  veoValidation?: VeoValidation
}

export type ScanEvent =
  | { type: 'log'; message: string }
  | { type: 'reddit_log'; message: string }
  | { type: 'alibaba_log'; message: string }
  | { type: 'progress'; value: number }
  | { type: 'stream_url'; url: string; target?: 'shein' | 'alibaba' }
  | { type: 'result'; data: ScanResult }
  | { type: 'error'; message: string }

// ── Cart Cleanser / Sanitization ─────────────────────────────────────────────

export type JunkFee = {
  name: string
  amount: string
  description: string
}

export type ProductOrigin = {
  isDropshipped: boolean
  wholesalePriceEstimate: string
  markupPercentage: string
  likelySourcedFrom: string
  analysis: string
}

export type SanitizationResult = {
  basePrice: string
  junkFeesRemoved: JunkFee[]
  finalPrice: string
  screenshotUrl?: string
  trustScore?: number
  fakeReviewsDetected?: boolean
  productOrigin?: ProductOrigin
  spatialValidation?: SpatialValidation
  actionRecommendation?: ActionRecommendation
}

export type CleanCartEvent =
  | { type: 'log'; message: string; level: 'info' | 'warn' | 'action' | 'vision' | 'success' }
  | { type: 'stream_url'; url: string }
  | { type: 'result'; data: SanitizationResult }
  | { type: 'error'; message: string }
